# Wazuh Docker Copyright (C) 2019 Wazuh Inc. (License GPLv2)

# Wazuh - Filebeat configuration file
filebeat.inputs:
  - type: log
    paths:
      - '/var/ossec/logs/alerts/alerts.json'

setup.template.json.enabled: true
setup.template.json.path: "/etc/filebeat/wazuh-template.json"
setup.template.json.name: "wazuh"
setup.template.overwrite: true


output.elasticsearch:
  hosts: ['http://odfe:9200']
  #pipeline: geoip
  indices:
    - index: 'wazuh-alerts-4.x-%{+yyyy.MM.dd}'
